version: "1.0"
services:
  ubuntu:
    image: "${IMAGE_PATH}"
    container_name: ubuntu
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - VSC_PASSWORD=${VSC_PASSWORD}
      - VSC_ENABLE=${VSC_ENABLE}
    volumes:
      - extdisk:/mydata
    ports:
      - 80:80
    restart: unless-stopped
  ubuntu2:
    image: "${IMAGE_PATH}"
    container_name: ubuntu2
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - VSC_PASSWORD=${VSC_PASSWORD}
    restart: unless-stopped
  postgresql:
    image: "postgres:9.5.25-alpine"
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=p9Db7W7C68ccf4
      - PGDATA=/mydata/pgdata
    volumes:
      - extdisk:/mydata
    restart: unless-stopped
volumes:
  extdisk:
    driver_opts:
      class: standard
      size: 5Gi
