version: "1.0"
services:
  ubuntu:
    image: "${IMAGE_PATH}"
    container_name: ubuntu
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - VSC_PASSWORD=${VSC_PASSWORD}
      - VSC_ENABLE=${VSC_ENABLE}
    volumes:
      - extdisk:/mydata
    ports:
      - 80:80
    restart: unless-stopped
  ubuntu2:
    image: "${IMAGE_PATH}"
    container_name: ubuntu2
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - VSC_PASSWORD=${VSC_PASSWORD}
    restart: unless-stopped
  nginx:
    image: "nginx"
    container_name: nginx
    restart: unless-stopped
volumes:
  extdisk:
    driver_opts:
      class: standard
      size: 5Gi
